name: 🐛 Bug Report
description: Report a problem with the Open Fields software or protocols
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please complete the form below so we can help.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Hardware, OS, or board you're using (e.g. ESP32, Raspberry Pi, LoRa type)
      placeholder: e.g. ESP32-S3, Ubuntu 20.04, Dragino LG01

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Connect device
        2. Start data logger
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Data should be saved and transmitted to mesh server.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Device rebooted and lost data.

  - type: input
    id: version
    attributes:
      label: Project Version
      description: Use `git describe` or `--version` if available
      placeholder: v0.3.2, commit 71abf8e

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Output
      description: Add logs, error messages, or screenshots if possible.
      placeholder: |
        [ 12.034 ] LoRa init failed
        [ 12.235 ] Rebooting...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
    validations:
      required: true
