blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Start a Discussion
    url: https://github.com/openfieldsproject/openfields-core/discussions
    about: For general questions, design feedback, or ideas, please use Discussions.
