name: ✨ Feature Request
description: Suggest a new feature or improvement
labels: [enhancement, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! Please describe it clearly below.

  - type: textarea
    id: summary
    attributes:
      label: Feature Description
      description: What would you like to see added or improved?
      placeholder: I’d like a way to view sensor trends on a local dashboard.

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Why is this feature needed? Who benefits from it?
      placeholder: Helps farmers monitor water use without needing internet.

  - type: dropdown
    id: importance
    attributes:
      label: Priority / Urgency
      description: How important is this feature to your use case?
      options:
        - Critical (blocking real-world deployment)
        - High
        - Medium
        - Nice to have

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes or Resources
      description: Mockups, links, related issues, or prior art.
      placeholder: Screenshots, CLI output, or examples.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project’s [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true
